name = "workout-tracker"
main = "src/worker.js"
compatibility_date = "2026-07-31"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false
routes = [{ pattern = "workout.lagrangee.xyz", custom_domain = true, previews_enabled = false }]

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "workout-tracker"
database_id = "157c8936-701e-493d-92ad-b45f0d91aae0"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "production"
DEFAULT_TIMEZONE = "Asia/Shanghai"
PRODUCTION_HOST = "workout.lagrangee.xyz"
